refactor: all project

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -25,8 +25,13 @@ fi
 node dist/server.js &
 node_pid=$!
 
+# TODO: quizas los script de test tendrian que estart en la libreria comun
 while ! nc -z localhost "$PORT"; do
   echo "Waiting for server to start..."
+  if ! kill -0 $node_pid 2>/dev/null; then
+    echo -e "\e[1;31mServer failed to start\e[0m"
+    exit 1
+  fi
   sleep 0.3
 done
 
